services:
  qbt-sync:
    restart: unless-stopped
    build: .
    networks:
      - traefik
    volumes:
      - "./.user_credentials.yml:/app/.user_credentials.yml:ro"
      - "./tags.yml:/app/tags.yml:ro"

networks:
  traefik:
    external: true
